// src/components/Node.tsx
import {
  type Component,
  For,
  Match,
  Show,
  Switch,
  createSignal,
  useContext,
} from 'solid-js'
import { globalOptionsContext, highlightedSpanSignal } from '../state'

interface Props {
  node: any
  hideHead?: boolean
}

function isSpanLike(object: any) {
  return (
    Object.keys(object).length === 2 &&
    typeof object.start === 'number' &&
    typeof object.end === 'number'
  )
}

const Node: Component<Props> = (props) => {
  const [expanded, setExpanded] = createSignal(true)
  const [childrenExpanded, setChildrenExpanded] = createSignal(
    Object.fromEntries(Object.keys(props.node).map((key) => [key, true]))
  )
  const [globalOptions] = useContext(globalOptionsContext)
  const [hovered, setHovered] = createSignal(false)
  const [, setHighlightedSpan] = highlightedSpanSignal

  const handleMouseOver = (event: MouseEvent) => {
    if (!globalOptions.highlightOnHover) {
      return
    }
    event.stopPropagation()
    setHovered(true)
    if (props.node.span) {
      setHighlightedSpan(props.node.span)
    } else if (isSpanLike(props.node)) {
      setHighlightedSpan(props.node)
    }
  }

  const handleMouseOut = (event: MouseEvent) => {
    if (!globalOptions.highlightOnHover) {
      return
    }
    event.stopPropagation()
    setHovered(false)
    setHighlightedSpan(null)
  }

  const properties = () =>
    Object.entries(props.node).filter(
      ([key]) =>
        (!globalOptions.hideSpan || key !== 'span') &&
        (!globalOptions.hideType || key !== 'type')
    )

  return (
    <div
      class="flex flex-col rounded-sm"
      classList={{ 'bg-light-600': hovered() }}
      onMouseOver={handleMouseOver}
      onMouseOut={handleMouseOut}
    >
      <Show when={!props.hideHead}>
        <button
          class="outline-none border-none bg-none h-min flex"
          onClick={() => setExpanded(!expanded())}
        >
          <div class="w-4">
            <Show
              when={expanded()}
              fallback={<i class="fa-solid fa-caret-right"></i>}
            >
              <i class="fa-solid fa-caret-down"></i>
            </Show>
          </div>
          <span>
            <Show when={isSpanLike(props.node)} fallback={props.node.type}>
              Span
            </Show>
          </span>
        </button>
      </Show>
      <ul
        class="list-none ml-4"
        classList={{ hidden: !expanded() && !props.hideHead }}
      >
        <For each={properties()}>
          {([key, value]) => (
            <li>
              <Switch>
                <Match when={Array.isArray(value)}>
                  <button
                    class="h-min flex items-center"
                    onClick={() =>
                      setChildrenExpanded((state) => ({
                        ...state,
                        [key]: !state[key],
                      }))}
                  >
                    <span class="w-4">
                      <Switch
                        fallback={<i class="fa-solid fa-caret-right"></i>}
                      >
                        <Match when={(value as unknown[]).length === 0}>
                          &nbsp;
                        </Match>
                        <Match when={childrenExpanded()[key]}>
                          <i class="fa-solid fa-caret-down"></i>
                        </Match>
                      </Switch>
                    </span>
                    <code class="text-purple-800">{key}</code>:
                    <span class="ml-3 text-sm">
                      <Switch
                        fallback={
                          <span>
                            [ {(value as unknown[]).length} elements ]
                          </span>
                        }
                      >
                        <Match when={(value as unknown[]).length === 0}>
                          <i>(empty array)</i>
                        </Match>
                        <Match when={(value as unknown[]).length === 1}>
                          <span>[ 1 element ]</span>
                        </Match>
                      </Switch>
                    </span>
                  </button>
                  <div
                    class="ml-4"
                    classList={{ hidden: childrenExpanded()[key] }}
                  >
                    <For each={value as unknown[]}>
                      {(item) => <Node node={item} />}
                    </For>
                  </div>
                </Match>
                <Match when={typeof value === 'object' && value != null}>
                  <button
                    class="h-min flex items-center"
                    onClick={() =>
                      setChildrenExpanded((state) => ({
                        ...state,
                        [key]: !state[key],
                      }))}
                  >
                    <span class="w-4">
                      <Show
                        when={childrenExpanded()[key]}
                        fallback={<i class="fa-solid fa-caret-right"></i>}
                      >
                        <i class="fa-solid fa-caret-down"></i>
                      </Show>
                    </span>
                    <code class="text-purple-800">{key}</code>:
                    <Show
                      when={typeof (value as { type?: string }).type ===
                        'string'}
                    >
                      <span class="ml-3">
                        {(value as { type: string }).type}
                      </span>
                    </Show>
                  </button>
                  <Show when={childrenExpanded()[key]}>
                    <Node node={value} hideHead />
                  </Show>
                </Match>
                <Match when={typeof value === 'string'}>
                  <span class="ml-4 mr-1">
                    <code class="text-purple-800">{key}</code>:
                  </span>
                  <code class="text-rose-800 ml-1">{value as string}</code>
                </Match>
                <Match when={typeof value === 'number'}>
                  <span class="ml-4 mr-1">
                    <code class="text-purple-800">{key}</code>:
                  </span>
                  <code class="text-yellow-700 ml-1">{value as number}</code>
                </Match>
                <Match when={typeof value === 'boolean' || value === null}>
                  <span class="ml-4 mr-1">
                    <code class="text-purple-800">{key}</code>:
                  </span>
                  <code class="text-sky-700 ml-1">{String(value)}</code>
                </Match>
              </Switch>
            </li>
          )}
        </For>
      </ul>
    </div>
  )
}

export default Node

// src/components/Node.svelte
<script lang="ts">
  import { globalOptions, highlightedSpan } from '../state.svelte.js'
  import Node from './Node.svelte'

  let { node, hideHead }: {
    node: any,
    hideHead?: boolean,
  } = $props()

  let expanded = $state(true)
  let childrenExpanded = $state(
    Object.fromEntries(Object.keys(node).map((key) => [key, true])),
  )
  let hovered = $state(false)
  let properties = $derived(
    Object.entries(node).filter(
      ([key]) =>
        (!globalOptions.hideSpan || key !== 'span') &&
        (!globalOptions.hideType || key !== 'type'),
    ),
  )

  function isSpanLike(object: any) {
    return (
      Object.keys(object).length === 2 &&
      typeof object.start === 'number' &&
      typeof object.end === 'number'
    )
  }

  const select = (event: MouseEvent | FocusEvent) => {
    if (!globalOptions.highlightOnHover) {
      return
    }
    event.stopPropagation()
    hovered = true
    if (node.span) {
      highlightedSpan.set(node.span)
    } else if (isSpanLike(node)) {
      highlightedSpan.set(node)
    }
  }

  const unselect = (event: MouseEvent | FocusEvent) => {
    if (!globalOptions.highlightOnHover) {
      return
    }
    event.stopPropagation()
    hovered = false
    highlightedSpan.set(null)
  }
</script>

<div
  class="flex flex-col rounded-sm node"
  class:hovered
  role="listitem"
  onmouseover={select}
  onfocus={select}
  onmouseout={unselect}
  onblur={unselect}
>
  {#if !hideHead}
    <button
      class="outline-none border-none bg-none h-min flex"
      onclick={() => expanded = !expanded}
    >
      <div class="w-4">
        {#if expanded}
          <i class="fa-solid fa-caret-down"></i>
        {:else}
          <i class="fa-solid fa-caret-right"></i>
        {/if}
      </div>
      <span>
        {#if isSpanLike(node)}
          Span
        {:else}
          {node.type}
        {/if}
      </span>
    </button>
  {/if}
  <ul class="list-none ml-4" class:hidden={!expanded && !hideHead}>
    {#each properties as [key, value]}
      <li>
        {#if Array.isArray(value)}
          <button
            class="h-min flex items-center"
            onclick={() => childrenExpanded[key] = !childrenExpanded[key]}
          >
            <span class="w-4">
              {#if value.length === 0}
                &nbsp;
              {:else if childrenExpanded[key]}
                <i class="fa-solid fa-caret-down"></i>
              {:else}
                <i class="fa-solid fa-caret-right"></i>
              {/if}
            </span>
            <code class="text-purple-800">{key}</code>:
            <span class="ml-3 text-sm">
              {#if value.length === 0}
                <i>(empty array)</i>
              {:else if value.length === 1}
                <span>[ 1 element ]</span>
              {:else}
                <span>[ {value.length} elements ]</span>
              {/if}
            </span>
          </button>
          <div class="ml-4" class:hidden={childrenExpanded[key]}>
            {#each value as item}
              <Node node={item} />
            {/each}
          </div>
        {:else if typeof value === 'object' && value != null}
          <button
            class="h-min flex items-center"
            onclick={() => childrenExpanded[key] = !childrenExpanded[key]}
          >
            <span class="w-4">
              {#if childrenExpanded[key]}
                <i class="fa-solid fa-caret-down"></i>
              {:else}
                <i class="fa-solid fa-caret-right"></i>
              {/if}
            </span>
            <code class="text-purple-800">{key}</code>:
            {#if 'type' in value && typeof value.type === 'string'}
              <span class="ml-3">
                {value.type}
              </span>
            {/if}
          </button>
          {#if childrenExpanded[key]}
            <Node node={value} hideHead />
          {/if}
        {:else if typeof value === 'string'}
          <span class="ml-4 mr-1">
            <code class="text-purple-800">{key}</code>:
          </span>
          <code class="text-rose-800 ml-1">{value}</code>
        {:else if typeof value === 'number'}
          <span class="ml-4 mr-1">
            <code class="text-purple-800">{key}</code>:
          </span>
          <code class="text-yellow-700 ml-1">{value}</code>
        {:else if typeof value === 'boolean' || value === null}
          <span class="ml-4 mr-1">
            <code class="text-purple-800">{key}</code>:
          </span>
          <code class="text-sky-700 ml-1">{String(value)}</code>
        {/if}
      </li>
    {/each}
  </ul>
</div>

<style>
  .node {
    display: flex;
    flex-direction: column;
  }
  .node.hovered {
    background-color: #f1f3f5;
  }

  .hidden {
    display: none;
  }
</style>
