// src/App.tsx
import {
  type Component,
  createSignal,
  Match,
  Switch,
  createResource,
  useContext,
  createEffect,
} from 'solid-js'
import { Ok, Err, type Result } from 'ts-results'
import { gzip, ungzip } from 'pako'
import { Base64 } from 'js-base64'
import Editor from './components/Editor'
import Header from './components/Header'
import JsonView from './components/JsonView'
import Node from './components/Node'
import { loadWasm, type ParseError } from './raffia'
import { globalOptionsContext } from './state'

const App: Component = () => {
  const [globalOptions, setGlobalOptions] = useContext(globalOptionsContext)
  const [code, setCode] = createSignal('')
  const [wasmURL] = createSignal('https://raffia.netlify.app/wasm.generated.js')
  const [parser] = createResource(wasmURL, loadWasm)

  const result = (): Result<unknown, ParseError> => {
    const parseStylesheet = parser()
    if (!parseStylesheet) {
      return Ok({})
    }
    try {
      return Ok(parseStylesheet(code(), globalOptions.syntax))
    } catch (error) {
      return Err(error as ParseError)
    }
  }

  createEffect(() => {
    const url = new URL(location.href)
    const encodedInput = url.searchParams.get('code')
    if (encodedInput) {
      setCode(ungzip(Base64.toUint8Array(encodedInput), { to: 'string' }))
    }

    const syntax = url.searchParams.get('syntax')
    if (syntax) {
      setGlobalOptions('syntax', syntax)
    }
  })

  function handleShare() {
    const url = new URL(location.href)
    url.searchParams.set('code', Base64.fromUint8Array(gzip(code())))
    url.searchParams.set('syntax', globalOptions.syntax)
    history.replaceState(null, '', url.toString())
    navigator.clipboard.writeText(url.toString())
  }

  return (
    <div>
      <Header onShare={handleShare} />
      <main class="grid grid-cols-2">
        <div>
          <Editor
            error={result().err ? (result().val as ParseError) : undefined}
            value={code()}
            onInput={setCode}
          />
        </div>
        <div
          class="border-l-width-1px p-2 bg-light-100 overflow-y-scroll"
          style={{ height: 'calc(100vh - 56px)' }}
        >
          <Switch>
            <Match when={parser.loading}>Loading WebAssembly module...</Match>
            <Match when={result().err}>{(result().val as ParseError)[1]}</Match>
            <Match when={globalOptions.view === 'tree'}>
              <Node node={result().val} />
            </Match>
            <Match when={globalOptions.view === 'json'}>
              <JsonView ast={result().val} />
            </Match>
          </Switch>
        </div>
      </main>
    </div>
  )
}

export default App

// src/App.svelte
<script lang="ts">
  import { Base64 } from 'js-base64'
  import { gzip, ungzip } from 'pako'
  import { onMount } from 'svelte'
  import { Err, Ok } from 'ts-results'
  import Editor from './components/Editor.svelte'
  import Header from './components/Header.svelte'
  import JsonView from './components/JsonView.svelte'
  import Node from './components/Node.svelte'
  import { type ParseError, type Parser, loadWasm } from './raffia'
  import { globalOptions } from './state.svelte.js'

  const STORAGE_KEY_CODE = 'v1.code'
  const STORAGE_KEY_SYNTAX = 'v1.syntax'

  let code = $state('')
  let parser: Parser | null = $state(null)

  let result = $derived.by(() => {
    if (!parser) {
      return Ok({})
    }
    try {
      return Ok(parser(code, globalOptions.syntax))
    } catch (error) {
      return Err(error as ParseError)
    }
  })

  onMount(async () => {
    const url = new URL(location.href)
    const encodedInput = url.searchParams.get('code')
    const storedInput = localStorage.getItem(STORAGE_KEY_CODE)
    if (encodedInput) {
      code = ungzip(Base64.toUint8Array(encodedInput), { to: 'string' })
    } else if (storedInput) {
      code = storedInput
    }

    const encodedSyntax = url.searchParams.get('syntax')
    const storedSyntax = localStorage.getItem(STORAGE_KEY_SYNTAX)
    if (encodedSyntax) {
      globalOptions.syntax = encodedSyntax
    } else if (storedSyntax) {
      globalOptions.syntax = storedSyntax
    }

    parser = await loadWasm()
  })

  $effect(() => {
    localStorage.setItem(STORAGE_KEY_CODE, code)
    localStorage.setItem(STORAGE_KEY_SYNTAX, globalOptions.syntax)
  })

  function handleShare() {
    const url = new URL(location.href)
    url.searchParams.set('code', Base64.fromUint8Array(gzip(code)))
    url.searchParams.set('syntax', globalOptions.syntax)
    history.replaceState(null, '', url.toString())
    navigator.clipboard.writeText(url.toString())
  }
</script>

<div>
  <Header onshare={handleShare} />
  <main class="grid grid-cols-2">
    <div>
      <Editor
        error={result.err ? result.val : undefined}
        value={code}
        oninput={(value) => code = value}
      />
    </div>
    <div class="bg-light-100 right-side">
      {#if !parser}
        Loading WebAssembly module...
      {:else if result.err}
        {result.val[1]}
      {:else if globalOptions.view === 'tree'}
        <Node node={result.val} />
      {:else if globalOptions.view === 'json'}
        <JsonView ast={result.val} />
      {/if}
    </div>
  </main>
</div>

<style>
  .right-side {
    border-left-width: 1px;
    padding: 0.5rem;
    overflow-y: scroll;
    height: calc(100vh - 56px);
  }
</style>
